# Project information
site_name: Telugu-exp data analysis
site_url: https://somanath08.github.io/Telugu-Analysis
site_author: Sai Somanath Komanduri
site_description: >-
  A website that shows the analysis of the data collected throught both the online and offlin
  versions of the experiment.
# Repository
repo_name: somanath08/Telugu-Analysis
repo_url: https://github.com/somanath08/Telugu-Analysis
edit_uri: ''

# Copyright
copyright: Copyright &copy; 2020 Sai Somanath Komanduri

# Configuration
theme:
  name: material
  logo: images/logo.png

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    primary: black
    accent: deep orange
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/logo.png

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: somanath08
      repo: Telugu-Analysis
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# For MathJax
extra_javascript:
  # - js/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
